package com.wjn.androiddbdemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wjn.androiddbdemo.greendao.People;
import com.wjn.androiddbdemo.greendao.UserInfo;

import com.wjn.androiddbdemo.greendao.PeopleDao;
import com.wjn.androiddbdemo.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig peopleDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final PeopleDao peopleDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        peopleDaoConfig = daoConfigMap.get(PeopleDao.class).clone();
        peopleDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        peopleDao = new PeopleDao(peopleDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(People.class, peopleDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        peopleDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public PeopleDao getPeopleDao() {
        return peopleDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
